// API Endpoints - Auto-generated from OpenAPI specification
// This file is auto-generated by scripts/generate-types-enhanced.sh
// Do not edit this file directly. Changes will be overwritten.

import { AUDIO_FILES_ENDPOINTS } from './audio-files.types'
import { AUTH_ENDPOINTS } from './auth.types'
import { DJS_ENDPOINTS } from './djs.types'
import { HEALTH_ENDPOINTS } from './health.types'
import { IMAGE_FILES_ENDPOINTS } from './image-files.types'
import { INVITATIONS_ENDPOINTS } from './invitations.types'
import { MIX_SESSIONS_ENDPOINTS } from './mix-sessions.types'
import { MIXTAPES_ENDPOINTS } from './mixtapes.types'
import { SESSIONS_ENDPOINTS } from './sessions.types'
import { STREAM_ENDPOINTS } from './stream.types'
import { TAGS_ENDPOINTS } from './tags.types'
import { USERS_ENDPOINTS } from './users.types'

/**
 * Aggregated API endpoints for all domains
 * Auto-generated from OpenAPI specification
 */
export const API_ENDPOINTS = {
  AUDIO_FILES: AUDIO_FILES_ENDPOINTS,
  AUTH: AUTH_ENDPOINTS,
  DJS: DJS_ENDPOINTS,
  HEALTH: HEALTH_ENDPOINTS,
  IMAGE_FILES: IMAGE_FILES_ENDPOINTS,
  INVITATIONS: INVITATIONS_ENDPOINTS,
  MIX_SESSIONS: MIX_SESSIONS_ENDPOINTS,
  MIXTAPES: MIXTAPES_ENDPOINTS,
  SESSIONS: SESSIONS_ENDPOINTS,
  STREAM: STREAM_ENDPOINTS,
  TAGS: TAGS_ENDPOINTS,
  USERS: USERS_ENDPOINTS,
} as const

export type ApiEndpoints = typeof API_ENDPOINTS
