// Modular API Types - Intelligent auto-detection
// Generated by analyzing actual API structure patterns

// Global types (full export for compatibility)
export type { components, paths, operations } from './globals.types';

// Domain-specific types (auto-detected)
export * from './auth.types';
export * from './users.types';
export * from './audio-files.types';
export * from './image-files.types';
export * from './health.types';
export * from './stream.types';
export * from './invitations.types';
export * from './djs.types';
export * from './mixtapes.types';
export * from './sessions.types';
export * from './mix-sessions.types';
export * from './tags.types';
