/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/auth/login': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** User login */
    post: operations['AuthController_signIn']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/auth/register': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** User registration */
    post: operations['AuthController_signUp']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/auth/refresh': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Refresh access token */
    post: operations['AuthController_refreshTokens']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/auth/logout': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** User logout */
    post: operations['AuthController_signOut']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/auth/profile': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Get user profile */
    get: operations['AuthController_getProfile']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/users': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Get all users with pagination and filters
     * @description Retrieve a paginated list of users with optional filtering by role and profile status. Requires authentication and admin privileges.
     */
    get: operations['UsersController_findAll']
    put?: never
    /**
     * Create a new user
     * @description Create a new user account. Requires authentication and admin privileges.
     */
    post: operations['UsersController_create']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/users/{id}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Get user by ID
     * @description Retrieve a specific user by their ID. Requires authentication and admin privileges.
     */
    get: operations['UsersController_findOne']
    put?: never
    post?: never
    /**
     * Delete user
     * @description Delete an existing user. Requires authentication and admin privileges.
     */
    delete: operations['UsersController_remove']
    options?: never
    head?: never
    /**
     * Update user
     * @description Update an existing user. Requires authentication and admin privileges.
     */
    patch: operations['UsersController_update']
    trace?: never
  }
  '/users/{id}/profile': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * Create user profile
     * @description Create a profile for a user. Requires authentication and admin privileges.
     */
    post: operations['UsersController_createProfile']
    delete?: never
    options?: never
    head?: never
    /**
     * Update user profile
     * @description Update a user's profile information. Requires authentication and admin privileges.
     */
    patch: operations['UsersController_updateProfile']
    trace?: never
  }
  '/djs': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Get all DJs with pagination and filters
     * @description Retrieve all DJs with optional filtering by mixtape presence and search capabilities.
     */
    get: operations['DjsController_findAll']
    put?: never
    /**
     * Create a new DJ
     * @description Create a new DJ with automatic slug generation.
     */
    post: operations['DjsController_create']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/djs/{id}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Get DJ by ID
     * @description Retrieve a specific DJ by their unique identifier.
     */
    get: operations['DjsController_findOne']
    put?: never
    post?: never
    /**
     * Delete DJ
     * @description Delete a DJ by ID.
     */
    delete: operations['DjsController_remove']
    options?: never
    head?: never
    /**
     * Update DJ
     * @description Update an existing DJ by ID.
     */
    patch: operations['DjsController_update']
    trace?: never
  }
  '/djs/{id}/mixtapes': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Get DJ mixtapes
     * @description Retrieve all mixtapes associated with a specific DJ.
     */
    get: operations['DjsController_getDjMixtapes']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/health': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Health check endpoint */
    get: operations['HealthController_healthCheck']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/images': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Get all images with pagination and filters
     * @description Retrieve a paginated list of images with optional filtering by bucket, MIME type, and search capabilities.
     */
    get: operations['ImagesController_findAll']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/images/upload': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * Upload an image
     * @description Upload an image file with automatic processing and thumbnail generation.
     */
    post: operations['ImagesController_upload']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/images/metadata/{id}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Get image metadata by ID
     * @description Retrieve metadata for a specific image by its ID.
     */
    get: operations['ImagesController_findOne']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/images/{id}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Serve image file by ID
     * @description Serve the original image file by its ID.
     */
    get: operations['ImagesController_serveImageById']
    put?: never
    post?: never
    /**
     * Delete image
     * @description Delete an existing image and its files.
     */
    delete: operations['ImagesController_remove']
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/images/{id}/thumbnail': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Serve image thumbnail by ID
     * @description Serve the thumbnail version of an image by its ID.
     */
    get: operations['ImagesController_serveThumbnailById']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/images/{bucket}/{filename}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Serve image file by URI
     * @description Serve the original image file using bucket/filename URI format.
     */
    get: operations['ImagesController_serveByUri']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/images/{bucket}/thumb/{filename}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Serve thumbnail by URI
     * @description Serve the thumbnail image file using bucket/thumb/filename URI format.
     */
    get: operations['ImagesController_serveThumbnailByUri']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/mixtapes': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Get all mixtapes with pagination and filters
     * @description Retrieve a paginated list of mixtapes with optional filtering by tags, DJ, year range, and search. Supports sorting and pagination.
     */
    get: operations['MixtapesController_findAll']
    put?: never
    /**
     * Create a new mixtape
     * @description Create a new mixtape with optional tags that will be auto-created if they don't exist. Requires authentication.
     */
    post: operations['MixtapesController_create']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/mixtapes/{id}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Get mixtape by ID
     * @description Retrieve a specific mixtape by its ID with cover information. Requires authentication.
     */
    get: operations['MixtapesController_findOne']
    put?: never
    post?: never
    /**
     * Delete mixtape
     * @description Delete an existing mixtape and its associated cover image. Requires authentication.
     */
    delete: operations['MixtapesController_remove']
    options?: never
    head?: never
    /**
     * Update mixtape
     * @description Update an existing mixtape. Requires authentication.
     */
    patch: operations['MixtapesController_update']
    trace?: never
  }
  '/mixtapes/{id}/cover/{imageId}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    /**
     * Set mixtape cover
     * @description Associate an image as the cover for a mixtape. Requires authentication.
     */
    put: operations['MixtapesController_updateCover']
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/mixtapes/{id}/cover': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    post?: never
    /**
     * Remove mixtape cover
     * @description Remove the cover from a mixtape and delete the associated image file.
     */
    delete: operations['MixtapesController_removeCover']
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/mixtapes/{id}/tags': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Get mixtape tags
     * @description Retrieve all tags associated with a specific mixtape.
     */
    get: operations['MixtapesController_getMixtapeTags']
    put?: never
    /**
     * Add tags to mixtape
     * @description Add multiple tags to a mixtape. Tags will be created automatically if they do not exist.
     */
    post: operations['MixtapesController_addTagsToMixtape']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/mixtapes/{id}/tags/{tagId}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    post?: never
    /**
     * Remove tag from mixtape
     * @description Remove a specific tag from a mixtape.
     */
    delete: operations['MixtapesController_removeTagFromMixtape']
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/mixtapes/{id}/djs': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Get mixtape DJs
     * @description Retrieve all DJs associated with a specific mixtape.
     */
    get: operations['MixtapesController_getMixtapeDjs']
    put?: never
    /**
     * Add DJs to mixtape
     * @description Add multiple DJs to a mixtape. DJs will be created automatically if they do not exist.
     */
    post: operations['MixtapesController_addDjsToMixtape']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/mixtapes/{id}/djs/{djId}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    post?: never
    /**
     * Remove DJ from mixtape
     * @description Remove a specific DJ from a mixtape.
     */
    delete: operations['MixtapesController_removeDjFromMixtape']
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/tags': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Get all tags with pagination and filters
     * @description Retrieve all tags with optional filtering by usage in mixtapes and search capabilities.
     */
    get: operations['TagsController_findAll']
    put?: never
    /**
     * Create a new tag
     * @description Create a new tag with automatic slug generation.
     */
    post: operations['TagsController_create']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/tags/{id}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Get tag by ID
     * @description Retrieve a specific tag by its unique identifier.
     */
    get: operations['TagsController_findOne']
    put?: never
    post?: never
    /**
     * Delete tag
     * @description Delete a tag by ID.
     */
    delete: operations['TagsController_remove']
    options?: never
    head?: never
    /**
     * Update tag
     * @description Update an existing tag by ID.
     */
    patch: operations['TagsController_update']
    trace?: never
  }
  '/tags/{id}/mixtapes': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Get tag mixtapes
     * @description Retrieve all mixtapes associated with a specific tag.
     */
    get: operations['TagsController_getTagMixtapes']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/stream/debug/listeners': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Debug endpoint for listeners data
     * @description Returns current listeners data for debugging purposes.
     */
    get: operations['StreamController_debugListeners']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/stream/debug/progress': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Debug endpoint for progress data
     * @description Returns current progress data for debugging purposes.
     */
    get: operations['StreamController_debugProgress']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/stream/debug/events': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Debug endpoint for events data
     * @description Returns current events data for debugging purposes.
     */
    get: operations['StreamController_debugEvents']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/stream/debug/all': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Debug endpoint for all stream data
     * @description Returns complete debug information for all streams.
     */
    get: operations['StreamController_debugAll']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/stream/events': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Stream events via Server-Sent Events
     * @description Real-time stream of combined AirTime and IceCast data including current track info, show details, and streaming metadata.
     */
    get: operations['StreamController_events']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/stream/listeners': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Stream listeners count via Server-Sent Events
     * @description Real-time stream of current listeners count from IceCast server.
     */
    get: operations['StreamController_listeners']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/stream/progress': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Stream track progress via Server-Sent Events
     * @description Real-time stream of current track progress percentage from AirTime scheduler.
     */
    get: operations['StreamController_progress']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
}
export type webhooks = Record<string, never>
export interface components {
  schemas: {
    SignInDto: {
      email: string
      password: string
    }
    SignUpDto: {
      email: string
      password: string
    }
    RefreshTokenDto: Record<string, never>
    Image: {
      /** @description Image unique identifier */
      id: string
      /** @description Original filename */
      originalName: string
      /**
       * @description Storage bucket
       * @default web
       */
      bucket: string
      /** @description MIME type */
      mimeType: string
      /** @description Image width in pixels */
      width: number
      /** @description Image height in pixels */
      height: number
      /** @description File size in bytes */
      size: number
      /** @description URI path of the file */
      uri: string
      /** @description Thumbnail URI path */
      thumbUri?: string
      /** @description Created by user */
      createdBy?: components['schemas']['User']
      /**
       * Format: date-time
       * @description Image creation date
       */
      createdAt: string
      /**
       * Format: date-time
       * @description Image last update date
       */
      updatedAt: string
    }
    Profile: {
      /** @description Profile unique identifier */
      id: string
      /** @description User nickname */
      nickname: string
      /** @description User description */
      description?: string
      /** @description User avatar */
      avatar?: components['schemas']['Image']
      /**
       * Format: date-time
       * @description Profile creation date
       */
      createdAt: string
      /**
       * Format: date-time
       * @description Profile last update date
       */
      updatedAt: string
    }
    User: {
      /** @description User unique identifier */
      id: string
      /** @description User email address */
      email: string
      /**
       * @description User role
       * @enum {string}
       */
      role: 'ADMIN' | 'MANAGER' | 'CONTRIBUTOR' | 'VIEWER'
      /**
       * Format: date-time
       * @description User creation date
       */
      createdAt: string
      /**
       * Format: date-time
       * @description User last update date
       */
      updatedAt: string
      /** @description User profile */
      profile: components['schemas']['Profile']
    }
    UsersListResponseDto: {
      data: components['schemas']['User'][]
      pagination: {
        /** @example 1 */
        page?: number
        /** @example 10 */
        limit?: number
        /** @example 42 */
        total?: number
        /** @example 5 */
        totalPages?: number
        /** @example true */
        hasNext?: boolean
        /** @example false */
        hasPrev?: boolean
      }
      /** @description Applied filters */
      filters: {
        [key: string]: unknown
      }
    }
    CreateUserDto: {
      /**
       * Format: email
       * @description User email address
       * @example user@example.com
       */
      email: string
      /**
       * @description User password
       * @example SecurePassword123!
       */
      password: string
    }
    UpdateUserDto: {
      /**
       * Format: email
       * @description User email address
       * @example user@example.com
       */
      email?: string
      /**
       * @description User password
       * @example SecurePassword123!
       */
      password?: string
    }
    UpdateUserProfileDto: {
      /**
       * @description User nickname or display name
       * @example DJ_Cool_Name
       */
      nickname?: string
      /**
       * @description Profile description or bio
       * @example Passionate DJ mixing electronic and hip-hop music
       */
      description?: string
      /**
       * @description Avatar image ID (optional, null to remove avatar)
       * @example 456e4567-e89b-12d3-a456-426614174001
       */
      avatarId?: string
    }
    Tag: {
      /** @description Tag unique identifier */
      id: string
      /** @description Tag name */
      name: string
      /** @description Tag slug */
      slug: string
      /** @description Tag color */
      color: string
      /** @description Tag mixtapes */
      mixtapes: components['schemas']['Mixtape'][]
      /** @description Created by user */
      createdBy?: components['schemas']['User']
      /**
       * Format: date-time
       * @description Tag creation date
       */
      createdAt: string
      /**
       * Format: date-time
       * @description Tag last update date
       */
      updatedAt: string
    }
    Mixtape: {
      /** @description Mixtape unique identifier */
      id: string
      /** @description Mixtape name */
      name: string
      /** @description Mixtape year */
      year: number
      /** @description Tracks as text */
      tracksAsText?: string
      /** @description Tracks as JSON */
      tracks?: Record<string, never>
      /** @description Mixtape description */
      description?: string
      /** @description Mixtape comment */
      comment?: string
      /** @description Mixtape cover */
      cover?: components['schemas']['Image']
      /** @description Mixtape tags */
      tags: components['schemas']['Tag'][]
      /** @description Mixtape DJs */
      djs: components['schemas']['Dj'][]
      /** @description Created by user */
      createdBy?: components['schemas']['User']
      /**
       * Format: date-time
       * @description Mixtape creation date
       */
      createdAt: string
      /**
       * Format: date-time
       * @description Mixtape last update date
       */
      updatedAt: string
    }
    Dj: {
      /** @description DJ unique identifier */
      id: string
      /** @description DJ name */
      name: string
      /** @description DJ slug */
      slug: string
      /** @description DJ mixtapes */
      mixtapes: components['schemas']['Mixtape'][]
      /** @description Created by user */
      createdBy?: components['schemas']['User']
      /**
       * Format: date-time
       * @description DJ creation date
       */
      createdAt: string
      /**
       * Format: date-time
       * @description DJ last update date
       */
      updatedAt: string
    }
    DjsListResponseDto: {
      /** @description The list of DJs */
      data: components['schemas']['Dj'][]
      /** @description Applied filters */
      filters: Record<string, never>
      /** @description Total number of records */
      total: number
      /** @description Current page number */
      page: number
      /** @description Number of records per page */
      limit: number
      /** @description Total number of pages */
      totalPages: number
    }
    DjResponseDto: {
      /** @description The DJ data */
      data: components['schemas']['Dj']
    }
    CreateDjDto: Record<string, never>
    UpdateDjDto: Record<string, never>
    MixtapesListResponseDto: {
      /** @description The list of mixtapes */
      data: components['schemas']['Mixtape'][]
      /** @description Applied filters */
      filters: Record<string, never>
      /** @description Total number of records */
      total: number
      /** @description Current page number */
      page: number
      /** @description Number of records per page */
      limit: number
      /** @description Total number of pages */
      totalPages: number
    }
    MixtapeResponseDto: {
      /** @description The mixtape data */
      data: components['schemas']['Mixtape']
    }
    CreateMixtapeDto: {
      /**
       * @description Mixtape name
       * @example Summer Vibes 2024
       */
      name: string
      /**
       * @description Release year
       * @example 2024
       */
      year: number
      /**
       * @description Tracks as text format
       * @example 1. Track One
       *     2. Track Two
       *     3. Track Three
       */
      tracksAsText?: string
      /**
       * @description Tracks as JSON format
       * @example [
       *       {
       *         "title": "Track One",
       *         "artist": "Artist Name",
       *         "duration": "3:45"
       *       }
       *     ]
       */
      tracks?: Record<string, never>
      /**
       * @description Mixtape description
       * @example A collection of summer hits
       */
      description?: string
      /**
       * @description Additional comments
       * @example Mixed by DJ Name
       */
      comment?: string
      /**
       * @description Cover image ID
       * @example 123e4567-e89b-12d3-a456-426614174000
       */
      coverId?: string
      /**
       * @description Array of tag names to associate with the mixtape (tags will be auto-created if they don't exist)
       * @example [
       *       "Electronic",
       *       "Deep House",
       *       "Summer"
       *     ]
       */
      tagNames?: string[]
      /**
       * @description Array of DJ names to associate with the mixtape (DJs will be auto-created if they don't exist)
       * @example [
       *       "DJ Shadow",
       *       "Bonobo",
       *       "Thievery Corporation"
       *     ]
       */
      djNames?: string[]
      /**
       * @description Default color for auto-created tags (hex format)
       * @default #6B7280
       * @example #3B82F6
       */
      defaultTagColor: string
    }
    UpdateMixtapeDto: {
      /**
       * @description Mixtape name
       * @example Summer Vibes 2024
       */
      name?: string
      /**
       * @description Release year
       * @example 2024
       */
      year?: number
      /**
       * @description Tracks as text format
       * @example 1. Track One
       *     2. Track Two
       *     3. Track Three
       */
      tracksAsText?: string
      /**
       * @description Tracks as JSON format
       * @example [
       *       {
       *         "title": "Track One",
       *         "artist": "Artist Name",
       *         "duration": "3:45"
       *       }
       *     ]
       */
      tracks?: Record<string, never>
      /**
       * @description Mixtape description
       * @example A collection of summer hits
       */
      description?: string
      /**
       * @description Additional comments
       * @example Mixed by DJ Name
       */
      comment?: string
      /**
       * @description Cover image ID
       * @example 123e4567-e89b-12d3-a456-426614174000
       */
      coverId?: string
      /**
       * @description Array of tag names to associate with the mixtape (tags will be auto-created if they don't exist)
       * @example [
       *       "Electronic",
       *       "Deep House",
       *       "Summer"
       *     ]
       */
      tagNames?: string[]
      /**
       * @description Array of DJ names to associate with the mixtape (DJs will be auto-created if they don't exist)
       * @example [
       *       "DJ Shadow",
       *       "Bonobo",
       *       "Thievery Corporation"
       *     ]
       */
      djNames?: string[]
      /**
       * @description Default color for auto-created tags (hex format)
       * @default #6B7280
       * @example #3B82F6
       */
      defaultTagColor: string
    }
    AddTagsToMixtapeDto: {
      /**
       * @description Array of tag names to add to the mixtape
       * @example [
       *       "Electronic",
       *       "Deep House",
       *       "Ambient"
       *     ]
       */
      tagNames: string[]
      /**
       * @description Default color for auto-created tags (hex format)
       * @default #6B7280
       * @example #3B82F6
       */
      defaultColor: string
    }
    AddDjsToMixtapeDto: {
      /**
       * @description List of DJ names to add to the mixtape
       * @example [
       *       "DJ Shadow",
       *       "Bonobo",
       *       "Thievery Corporation"
       *     ]
       */
      djNames: string[]
    }
    CreateTagDto: Record<string, never>
    TagsListResponseDto: {
      /** @description The list of tags */
      data: components['schemas']['Tag'][]
      /** @description Applied filters */
      filters: Record<string, never>
      /** @description Total number of records */
      total: number
      /** @description Current page number */
      page: number
      /** @description Number of records per page */
      limit: number
      /** @description Total number of pages */
      totalPages: number
    }
    TagResponseDto: {
      /** @description The tag data */
      data: components['schemas']['Tag']
    }
    UpdateTagDto: Record<string, never>
    IceCastDataDto: {
      /**
       * @description Audio info
       * @example mp3;44100;2
       */
      audio_info: string
      /**
       * @description Number of channels
       * @example 2
       */
      channels: number
      /**
       * @description Genre
       * @example Various
       */
      genre: string
      /**
       * @description Peak listeners count
       * @example 100
       */
      listener_peak: number
      /**
       * @description Current listeners count
       * @example 42
       */
      listeners: number
      /**
       * @description Listen URL
       * @example http://stream.nina.fm:8000/stream.mp3
       */
      listenurl: string
      /**
       * @description Sample rate
       * @example 44100
       */
      samplerate: number
      /**
       * @description Server description
       * @example NINA.FM
       */
      server_description: string
      /**
       * @description Server name
       * @example NINA.FM
       */
      server_name: string
      /**
       * @description Server type
       * @example icecast
       */
      server_type: string
      /**
       * @description Server URL
       * @example https://nina.fm
       */
      server_url: string
      /**
       * @description Stream start time
       * @example Mon, 01 Jul 2025 10:00:00 +0000
       */
      stream_start: string
      /**
       * @description Stream start time in ISO8601
       * @example 2025-07-01T10:00:00Z
       */
      stream_start_iso8601: string
      /**
       * @description Current track title
       * @example Artist - Track
       */
      title: string
    }
    AirTimeDataDto: {
      /**
       * @description Environment
       * @example production
       */
      env: string
      /**
       * @description Current time on scheduler
       * @example 2025-07-01 10:30:45
       */
      schedulerTime: string
      /** @description Previous track info */
      previous: Record<string, never>
      /** @description Current track info */
      current: Record<string, never>
      /** @description Next track info */
      next: Record<string, never>
      /** @description Current show info */
      currentShow: string[]
      /** @description Next show info */
      nextShow: string[]
      /**
       * @description Timezone
       * @example Europe/Paris
       */
      timezone: string
      /**
       * @description Timezone offset
       * @example +0200
       */
      timezoneOffset: string
      /**
       * @description AirTime API version
       * @example 2.5.1
       */
      AIRTIME_API_VERSION: string
    }
    EventsDataDto: {
      /** @description IceCast data */
      icecast: components['schemas']['IceCastDataDto']
      /** @description AirTime data */
      airtime: components['schemas']['AirTimeDataDto']
    }
    EventsResponseDto: {
      /** @description Combined stream events data */
      data: components['schemas']['EventsDataDto']
    }
    ListenersResponseDto: {
      /**
       * @description Current number of listeners
       * @example 42
       */
      data: number
    }
    ProgressResponseDto: {
      /**
       * @description Progress percentage of current track (0-100)
       * @example 45.67
       */
      data: number
    }
  }
  responses: never
  parameters: never
  requestBodies: never
  headers: never
  pathItems: never
}
export type $defs = Record<string, never>
export interface operations {
  AuthController_signIn: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['SignInDto']
      }
    }
    responses: {
      /** @description Returns access and refresh tokens */
      200: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
    }
  }
  AuthController_signUp: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['SignUpDto']
      }
    }
    responses: {
      /** @description Returns access and refresh tokens */
      200: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
    }
  }
  AuthController_refreshTokens: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['RefreshTokenDto']
      }
    }
    responses: {
      /** @description Returns new access and refresh tokens */
      200: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
    }
  }
  AuthController_signOut: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successfully logged out */
      200: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
    }
  }
  AuthController_getProfile: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Returns user profile */
      200: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
    }
  }
  UsersController_findAll: {
    parameters: {
      query?: {
        /** @description Numéro de page (commence à 1) */
        page?: number
        /** @description Nombre d'éléments par page */
        limit?: number
        /** @description Champ de tri */
        sortBy?: string
        /** @description Ordre de tri */
        sortOrder?: 'ASC' | 'DESC'
        /** @description Recherche textuelle globale */
        search?: string
        /** @description Filtrer par rôle utilisateur */
        role?: 'ADMIN' | 'MANAGER' | 'CONTRIBUTOR' | 'VIEWER'
        /** @description Filtrer par utilisateurs ayant un profil défini */
        hasProfile?: boolean
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Paginated list of users retrieved successfully */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['UsersListResponseDto']
        }
      }
      /** @description Unauthorized - Invalid or missing token */
      401: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Forbidden - Insufficient privileges */
      403: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
    }
  }
  UsersController_create: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['CreateUserDto']
      }
    }
    responses: {
      /** @description User created successfully */
      201: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Bad request - Invalid input data */
      400: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Unauthorized - Invalid or missing token */
      401: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Forbidden - Insufficient privileges */
      403: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Conflict - User already exists */
      409: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
    }
  }
  UsersController_findOne: {
    parameters: {
      query?: never
      header?: never
      path: {
        /** @description User unique identifier */
        id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description User retrieved successfully */
      200: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Unauthorized - Invalid or missing token */
      401: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Forbidden - Insufficient privileges */
      403: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description User not found */
      404: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
    }
  }
  UsersController_remove: {
    parameters: {
      query?: never
      header?: never
      path: {
        /** @description User unique identifier */
        id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description User deleted successfully */
      204: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Unauthorized - Invalid or missing token */
      401: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Forbidden - Insufficient privileges */
      403: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description User not found */
      404: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
    }
  }
  UsersController_update: {
    parameters: {
      query?: never
      header?: never
      path: {
        /** @description User unique identifier */
        id: string
      }
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['UpdateUserDto']
      }
    }
    responses: {
      /** @description User updated successfully */
      200: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Bad request - Invalid input data */
      400: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Unauthorized - Invalid or missing token */
      401: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Forbidden - Insufficient privileges */
      403: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description User not found */
      404: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
    }
  }
  UsersController_createProfile: {
    parameters: {
      query?: never
      header?: never
      path: {
        /** @description User unique identifier */
        id: string
      }
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['UpdateUserProfileDto']
      }
    }
    responses: {
      /** @description User profile created successfully */
      201: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Bad request - Invalid input data or user already has profile */
      400: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Unauthorized - Invalid or missing token */
      401: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Forbidden - Insufficient privileges */
      403: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description User not found */
      404: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
    }
  }
  UsersController_updateProfile: {
    parameters: {
      query?: never
      header?: never
      path: {
        /** @description User unique identifier */
        id: string
      }
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['UpdateUserProfileDto']
      }
    }
    responses: {
      /** @description User profile updated successfully */
      200: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Bad request - Invalid input data */
      400: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Unauthorized - Invalid or missing token */
      401: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Forbidden - Insufficient privileges */
      403: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description User not found */
      404: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
    }
  }
  DjsController_findAll: {
    parameters: {
      query?: {
        /** @description Numéro de page (commence à 1) */
        page?: number
        /** @description Nombre d'éléments par page */
        limit?: number
        /** @description Champ de tri */
        sortBy?: string
        /** @description Ordre de tri */
        sortOrder?: 'ASC' | 'DESC'
        /** @description Recherche textuelle globale */
        search?: string
        /** @description Filtrer par DJs ayant des mixtapes */
        hasMixtapes?: boolean
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Paginated list of DJs retrieved successfully */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['DjsListResponseDto']
        }
      }
      /** @description Unauthorized - Invalid or missing token */
      401: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
    }
  }
  DjsController_create: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['CreateDjDto']
      }
    }
    responses: {
      /** @description DJ created successfully */
      201: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Invalid input data */
      400: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Unauthorized - Invalid or missing token */
      401: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
    }
  }
  DjsController_findOne: {
    parameters: {
      query?: never
      header?: never
      path: {
        /** @description DJ unique identifier */
        id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description DJ retrieved successfully */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['DjResponseDto']
        }
      }
      /** @description Unauthorized - Invalid or missing token */
      401: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description DJ not found */
      404: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
    }
  }
  DjsController_remove: {
    parameters: {
      query?: never
      header?: never
      path: {
        /** @description DJ unique identifier */
        id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description DJ deleted successfully */
      200: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Unauthorized - Invalid or missing token */
      401: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description DJ not found */
      404: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
    }
  }
  DjsController_update: {
    parameters: {
      query?: never
      header?: never
      path: {
        /** @description DJ unique identifier */
        id: string
      }
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['UpdateDjDto']
      }
    }
    responses: {
      /** @description DJ updated successfully */
      200: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Invalid input data */
      400: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Unauthorized - Invalid or missing token */
      401: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description DJ not found */
      404: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
    }
  }
  DjsController_getDjMixtapes: {
    parameters: {
      query?: never
      header?: never
      path: {
        /** @description DJ unique identifier */
        id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description DJ mixtapes retrieved successfully */
      200: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Unauthorized - Invalid or missing token */
      401: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description DJ not found */
      404: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
    }
  }
  HealthController_healthCheck: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description API is healthy */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': {
            /** @example ok */
            status?: string
            /** @example 2025-07-06T12:00:00.000Z */
            timestamp?: string
            /** @example 3600 */
            uptime?: number
            /** @example production */
            environment?: string
            /** @example 1.0.0 */
            version?: string
          }
        }
      }
    }
  }
  ImagesController_findAll: {
    parameters: {
      query?: {
        /** @description Numéro de page (commence à 1) */
        page?: number
        /** @description Nombre d'éléments par page */
        limit?: number
        /** @description Champ de tri */
        sortBy?: string
        /** @description Ordre de tri */
        sortOrder?: 'ASC' | 'DESC'
        /** @description Recherche textuelle globale */
        search?: string
        /** @description Filtrer par type MIME */
        mimeType?: string
        /** @description Filtrer par bucket de stockage */
        bucket?: 'covers' | 'web'
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Paginated list of images retrieved successfully */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': {
            data?: components['schemas']['Image'][]
            pagination?: {
              /** @example 1 */
              page?: number
              /** @example 10 */
              limit?: number
              /** @example 42 */
              total?: number
              /** @example 5 */
              totalPages?: number
              /** @example true */
              hasNext?: boolean
              /** @example false */
              hasPrev?: boolean
            }
            /** @description Applied filters */
            filters?: Record<string, never>
          }
        }
      }
      /** @description Unauthorized - Invalid or missing token */
      401: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
    }
  }
  ImagesController_upload: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'multipart/form-data': {
          /**
           * Format: binary
           * @description Image file to upload (JPEG, PNG, GIF, WebP)
           */
          file?: string
          /**
           * @description Bucket to store the image in (optional, defaults to environment setting)
           * @example avatars
           */
          bucket?: string
        }
      }
    }
    responses: {
      /** @description Image uploaded successfully */
      201: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Bad request - No file or invalid file type */
      400: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Unauthorized - Invalid or missing token */
      401: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
    }
  }
  ImagesController_findOne: {
    parameters: {
      query?: never
      header?: never
      path: {
        /** @description Image unique identifier */
        id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Image metadata retrieved successfully */
      200: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Unauthorized - Invalid or missing token */
      401: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Image not found */
      404: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
    }
  }
  ImagesController_serveImageById: {
    parameters: {
      query?: never
      header?: never
      path: {
        /** @description Image unique identifier */
        id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Image file served successfully */
      200: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Image not found */
      404: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
    }
  }
  ImagesController_remove: {
    parameters: {
      query?: never
      header?: never
      path: {
        /** @description Image unique identifier */
        id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Image deleted successfully */
      204: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Unauthorized - Invalid or missing token */
      401: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Image not found */
      404: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
    }
  }
  ImagesController_serveThumbnailById: {
    parameters: {
      query?: never
      header?: never
      path: {
        /** @description Image unique identifier */
        id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Thumbnail served successfully */
      200: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Thumbnail not found */
      404: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
    }
  }
  ImagesController_serveByUri: {
    parameters: {
      query?: never
      header?: never
      path: {
        /** @description Storage bucket name */
        bucket: string
        /** @description Image filename with UUID */
        filename: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Image file served successfully */
      200: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Image not found */
      404: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
    }
  }
  ImagesController_serveThumbnailByUri: {
    parameters: {
      query?: never
      header?: never
      path: {
        /** @description Storage bucket name */
        bucket: string
        /** @description Image filename with UUID */
        filename: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Thumbnail served successfully */
      200: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Thumbnail not found */
      404: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
    }
  }
  MixtapesController_findAll: {
    parameters: {
      query?: {
        /** @description Numéro de page (commence à 1) */
        page?: number
        /** @description Nombre d'éléments par page */
        limit?: number
        /** @description Champ de tri */
        sortBy?: string
        /** @description Ordre de tri */
        sortOrder?: 'ASC' | 'DESC'
        /** @description Recherche textuelle globale */
        search?: string
        /** @description Filtrer par tags (noms) */
        tags?: string[]
        /** @description Filtrer par DJs (noms ou slugs) */
        djs?: string[]
        /** @description Filtrer par année exacte */
        year?: number
        /** @description Filtrer par année minimum */
        yearFrom?: number
        /** @description Filtrer par année maximum */
        yearTo?: number
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Paginated list of mixtapes retrieved successfully */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['MixtapesListResponseDto']
        }
      }
      /** @description Unauthorized - Invalid or missing token */
      401: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
    }
  }
  MixtapesController_create: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['CreateMixtapeDto']
      }
    }
    responses: {
      /** @description Mixtape created successfully with associated tags */
      201: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Bad request - Invalid input data or cover image not found */
      400: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Unauthorized - Invalid or missing token */
      401: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
    }
  }
  MixtapesController_findOne: {
    parameters: {
      query?: never
      header?: never
      path: {
        /** @description Mixtape unique identifier */
        id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Mixtape retrieved successfully */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['MixtapeResponseDto']
        }
      }
      /** @description Unauthorized - Invalid or missing token */
      401: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Mixtape not found */
      404: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
    }
  }
  MixtapesController_remove: {
    parameters: {
      query?: never
      header?: never
      path: {
        /** @description Mixtape unique identifier */
        id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Mixtape deleted successfully */
      204: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Unauthorized - Invalid or missing token */
      401: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Mixtape not found */
      404: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
    }
  }
  MixtapesController_update: {
    parameters: {
      query?: never
      header?: never
      path: {
        /** @description Mixtape unique identifier */
        id: string
      }
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['UpdateMixtapeDto']
      }
    }
    responses: {
      /** @description Mixtape updated successfully */
      200: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Bad request - Invalid input data */
      400: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Unauthorized - Invalid or missing token */
      401: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Mixtape not found */
      404: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
    }
  }
  MixtapesController_updateCover: {
    parameters: {
      query?: never
      header?: never
      path: {
        /** @description Mixtape unique identifier */
        id: string
        /** @description Image unique identifier */
        imageId: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Cover updated successfully */
      200: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Unauthorized - Invalid or missing token */
      401: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Mixtape or image not found */
      404: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
    }
  }
  MixtapesController_removeCover: {
    parameters: {
      query?: never
      header?: never
      path: {
        /** @description Mixtape unique identifier */
        id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Cover removed and image deleted successfully */
      200: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Unauthorized - Invalid or missing token */
      401: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Mixtape not found */
      404: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
    }
  }
  MixtapesController_getMixtapeTags: {
    parameters: {
      query?: never
      header?: never
      path: {
        /** @description Mixtape unique identifier */
        id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Mixtape tags retrieved successfully */
      200: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Unauthorized - Invalid or missing token */
      401: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Mixtape not found */
      404: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
    }
  }
  MixtapesController_addTagsToMixtape: {
    parameters: {
      query?: never
      header?: never
      path: {
        /** @description Mixtape unique identifier */
        id: string
      }
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['AddTagsToMixtapeDto']
      }
    }
    responses: {
      /** @description Tags added to mixtape successfully */
      200: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Bad request - Invalid input data */
      400: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Unauthorized - Invalid or missing token */
      401: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Mixtape not found */
      404: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
    }
  }
  MixtapesController_removeTagFromMixtape: {
    parameters: {
      query?: never
      header?: never
      path: {
        /** @description Mixtape unique identifier */
        id: string
        /** @description Tag unique identifier */
        tagId: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Tag removed from mixtape successfully */
      200: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Unauthorized - Invalid or missing token */
      401: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Mixtape or tag not found */
      404: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
    }
  }
  MixtapesController_getMixtapeDjs: {
    parameters: {
      query?: never
      header?: never
      path: {
        /** @description Mixtape ID */
        id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Mixtape DJs retrieved successfully */
      200: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Unauthorized - Invalid or missing token */
      401: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Mixtape not found */
      404: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
    }
  }
  MixtapesController_addDjsToMixtape: {
    parameters: {
      query?: never
      header?: never
      path: {
        /** @description Mixtape ID */
        id: string
      }
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['AddDjsToMixtapeDto']
      }
    }
    responses: {
      /** @description DJs added to mixtape successfully */
      200: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Unauthorized - Invalid or missing token */
      401: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Mixtape not found */
      404: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
    }
  }
  MixtapesController_removeDjFromMixtape: {
    parameters: {
      query?: never
      header?: never
      path: {
        /** @description Mixtape ID */
        id: string
        /** @description DJ ID to remove */
        djId: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description DJ removed from mixtape successfully */
      200: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Unauthorized - Invalid or missing token */
      401: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Mixtape not found */
      404: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
    }
  }
  TagsController_findAll: {
    parameters: {
      query?: {
        /** @description Numéro de page (commence à 1) */
        page?: number
        /** @description Nombre d'éléments par page */
        limit?: number
        /** @description Champ de tri */
        sortBy?: string
        /** @description Ordre de tri */
        sortOrder?: 'ASC' | 'DESC'
        /** @description Recherche textuelle globale */
        search?: string
        /** @description Filtrer par tags utilisés dans des mixtapes */
        hasUsage?: boolean
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Paginated list of tags retrieved successfully */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['TagsListResponseDto']
        }
      }
      /** @description Unauthorized - Invalid or missing token */
      401: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
    }
  }
  TagsController_create: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['CreateTagDto']
      }
    }
    responses: {
      /** @description Tag created successfully */
      201: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Invalid input data */
      400: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Unauthorized - Invalid or missing token */
      401: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
    }
  }
  TagsController_findOne: {
    parameters: {
      query?: never
      header?: never
      path: {
        /** @description Tag unique identifier */
        id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Tag retrieved successfully */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['TagResponseDto']
        }
      }
      /** @description Unauthorized - Invalid or missing token */
      401: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Tag not found */
      404: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
    }
  }
  TagsController_remove: {
    parameters: {
      query?: never
      header?: never
      path: {
        /** @description Tag unique identifier */
        id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Tag deleted successfully */
      200: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Unauthorized - Invalid or missing token */
      401: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Tag not found */
      404: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
    }
  }
  TagsController_update: {
    parameters: {
      query?: never
      header?: never
      path: {
        /** @description Tag unique identifier */
        id: string
      }
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['UpdateTagDto']
      }
    }
    responses: {
      /** @description Tag updated successfully */
      200: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Invalid input data */
      400: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Unauthorized - Invalid or missing token */
      401: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Tag not found */
      404: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
    }
  }
  TagsController_getTagMixtapes: {
    parameters: {
      query?: never
      header?: never
      path: {
        /** @description Tag unique identifier */
        id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Tag mixtapes retrieved successfully */
      200: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Unauthorized - Invalid or missing token */
      401: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Tag not found */
      404: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
    }
  }
  StreamController_debugListeners: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Current listeners debug information */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': {
            /** @description Current listeners count */
            current?: number
            /** @description Whether there are active observers */
            hasObservers?: boolean
            /** @description Number of active observers */
            observersCount?: number
          }
        }
      }
    }
  }
  StreamController_debugProgress: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Current progress debug information */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': {
            /** @description Current track progress percentage */
            current?: number
            /** @description Whether there are active observers */
            hasObservers?: boolean
            /** @description Number of active observers */
            observersCount?: number
          }
        }
      }
    }
  }
  StreamController_debugEvents: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Current events debug information */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': {
            /** @description Current events data */
            current?: {
              /** @description IceCast data */
              icecast?: Record<string, never>
              /** @description AirTime data */
              airtime?: Record<string, never>
            }
            /** @description Whether there are active observers */
            hasObservers?: boolean
            /** @description Number of active observers */
            observersCount?: number
          }
        }
      }
    }
  }
  StreamController_debugAll: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Complete debug information for all streams */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': {
            listeners?: {
              current?: number
              hasObservers?: boolean
              observersCount?: number
            }
            progress?: {
              current?: number
              hasObservers?: boolean
              observersCount?: number
            }
            events?: {
              current?: Record<string, never>
              hasObservers?: boolean
              observersCount?: number
            }
          }
        }
      }
    }
  }
  StreamController_events: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Stream events data */
      200: {
        headers: {
          /** @description text/event-stream */
          'Content-Type'?: unknown
          /** @description keep-alive */
          Connection?: unknown
          /** @description no-cache */
          'Cache-Control'?: unknown
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['EventsResponseDto']
        }
      }
    }
  }
  StreamController_listeners: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Current listeners count */
      200: {
        headers: {
          /** @description text/event-stream */
          'Content-Type'?: unknown
          /** @description keep-alive */
          Connection?: unknown
          /** @description no-cache */
          'Cache-Control'?: unknown
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ListenersResponseDto']
        }
      }
    }
  }
  StreamController_progress: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Current track progress percentage */
      200: {
        headers: {
          /** @description text/event-stream */
          'Content-Type'?: unknown
          /** @description keep-alive */
          Connection?: unknown
          /** @description no-cache */
          'Cache-Control'?: unknown
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ProgressResponseDto']
        }
      }
    }
  }
}
export enum ApiPaths {
  AuthController_signIn = '/auth/login',
  AuthController_signUp = '/auth/register',
  AuthController_refreshTokens = '/auth/refresh',
  AuthController_signOut = '/auth/logout',
  AuthController_getProfile = '/auth/profile',
  UsersController_findAll = '/users',
  UsersController_create = '/users',
  UsersController_findOne = '/users/{id}',
  UsersController_update = '/users/{id}',
  UsersController_remove = '/users/{id}',
  UsersController_updateProfile = '/users/{id}/profile',
  UsersController_createProfile = '/users/{id}/profile',
  DjsController_findAll = '/djs',
  DjsController_create = '/djs',
  DjsController_findOne = '/djs/{id}',
  DjsController_update = '/djs/{id}',
  DjsController_remove = '/djs/{id}',
  DjsController_getDjMixtapes = '/djs/{id}/mixtapes',
  HealthController_healthCheck = '/health',
  ImagesController_findAll = '/images',
  ImagesController_upload = '/images/upload',
  ImagesController_findOne = '/images/metadata/{id}',
  ImagesController_serveImageById = '/images/{id}',
  ImagesController_remove = '/images/{id}',
  ImagesController_serveThumbnailById = '/images/{id}/thumbnail',
  ImagesController_serveByUri = '/images/{bucket}/{filename}',
  ImagesController_serveThumbnailByUri = '/images/{bucket}/thumb/{filename}',
  MixtapesController_findAll = '/mixtapes',
  MixtapesController_create = '/mixtapes',
  MixtapesController_findOne = '/mixtapes/{id}',
  MixtapesController_update = '/mixtapes/{id}',
  MixtapesController_remove = '/mixtapes/{id}',
  MixtapesController_updateCover = '/mixtapes/{id}/cover/{imageId}',
  MixtapesController_removeCover = '/mixtapes/{id}/cover',
  MixtapesController_addTagsToMixtape = '/mixtapes/{id}/tags',
  MixtapesController_getMixtapeTags = '/mixtapes/{id}/tags',
  MixtapesController_removeTagFromMixtape = '/mixtapes/{id}/tags/{tagId}',
  MixtapesController_addDjsToMixtape = '/mixtapes/{id}/djs',
  MixtapesController_getMixtapeDjs = '/mixtapes/{id}/djs',
  MixtapesController_removeDjFromMixtape = '/mixtapes/{id}/djs/{djId}',
  TagsController_create = '/tags',
  TagsController_findAll = '/tags',
  TagsController_findOne = '/tags/{id}',
  TagsController_update = '/tags/{id}',
  TagsController_remove = '/tags/{id}',
  TagsController_getTagMixtapes = '/tags/{id}/mixtapes',
  StreamController_debugListeners = '/stream/debug/listeners',
  StreamController_debugProgress = '/stream/debug/progress',
  StreamController_debugEvents = '/stream/debug/events',
  StreamController_debugAll = '/stream/debug/all',
  StreamController_events = '/stream/events',
  StreamController_listeners = '/stream/listeners',
  StreamController_progress = '/stream/progress',
}
