create table "public"."tags" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone default now(),
    "name" text not null,
    "color" text
);


alter table "public"."tags" enable row level security;

CREATE UNIQUE INDEX tags_name_key ON public.tags USING btree (name);

CREATE UNIQUE INDEX tags_pkey ON public.tags USING btree (id);

alter table "public"."tags" add constraint "tags_pkey" PRIMARY KEY using index "tags_pkey";

alter table "public"."tags" add constraint "name_length" CHECK ((char_length(name) >= 1)) not valid;

alter table "public"."tags" validate constraint "name_length";

alter table "public"."tags" add constraint "tags_name_key" UNIQUE using index "tags_name_key";


create policy "Public tags are viewable by everyone."
on "public"."tags"
as permissive
for select
to public
using (true);

create policy "Enable insert for authenticated or anon."
on "public"."tags"
as permissive
for insert
to authenticated, anon
with check (true);

create policy "Enable update for authenticated or anon."
on "public"."tags"
as permissive
for update
to authenticated, anon
using (true);

create policy "Enable delete for authenticated or anon."
on "public"."tags"
as permissive
for delete
to authenticated, anon
using (true);



